### ISSUE TITLE
Radarbox failing to build in balena [Solved]

### ISSUE THREAD

**Issue by robinp26** [ketilmo/balena-ads-b#31]
[ads-b-raspberrypi_release-log_radarbox-437000f.txt](https://github.com/ketilmo/balena-ads-b/files/6722546/ads-b-raspberrypi_release-log_radarbox-437000f.txt)
![belenaerror](https://user-images.githubusercontent.com/6466458/123564441-806b3b00-d787-11eb-9ed5-882b4d24b134.png)

I created a new application using the 'Deploy with Belena' link but during build it fails to build the radarbox service.
The device chosen was Raspberry Pi 3. I tried deleting the application and re-creating again but it failed building again at the same spot.

Attached are the build logs for radarbox and a screenshot of the error.

**Comment by ketilmo** [comment]
Hi @robinp26,

Thanks for reporting this problem. After a quick investigation, it turns out that the reason is that Radarbox's key servers have been deprecated and not yet replaced. See the following Radarbox forum thread for more information: https://forum.radarbox24.com/index.php?topic=105261.0.

According to the information at https://sks-keyservers.net/, the key servers were deprecated on 21 June 2021. Hopefully, Radarbox will fix this very soon. In the meantime, I have added a workaround that allows for installing the service without the proper GPG keys.

The build should work again now. Please let me know if you have further issues.

Kind regards,
Ketil
